#!/bin/sh
[[ "$(uname)" = "Darwin" ]] && {
    brew install neovim yarn fish bat exa tokei hyperfine fd fzf tmux cmake aria2 youtube-dl meson mosh python3 ripgrep rsync plantuml graphviz
    brew cask install gitup db-browser-for-sqlite iterm2 middleclick provisionql riot sf-symbols signal wwdcsrt
    [[ "$(which gem)" != "/usr/local/opt/ruby/bin/gem" ]] && echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.zshrc
    brew upgrade
}
[[ "$(uname)" = "Linux" ]] && {
    hash dnf 2>/dev/null && {
        curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
        sudo dnf install -y neovim yarn fish bat exa tokei hyperfine fd-find fzf tmux gcc gcc-c++ openssl-devel libgit2-devel cmake youtube-dl aria2 cockpit meson mosh nasm python3 python3-devel python3-pip ripgrep rsync ruby-devel rubygems plantuml graphviz zlib-devel dbus-glib-devel clang
        sudo dnf update -y
    }
}

