#!/bin/bash
[[ "$(uname)" = "Darwin" ]] && {
    brew tap homebrew/cask-fonts
    brew tap vapor/tap
    brew install neovim fish bat exa tokei hyperfine fd fzf tmux cmake aria2 youtube-dl meson mosh python3 ripgrep rsync plantuml graphviz vapor/tap/vapor dust
    brew cask install gitup db-browser-for-sqlite iterm2 middleclick provisionql riot sf-symbols signal font-fira-code
    brew upgrade
    [[ "$(which gem)" != "/usr/local/opt/ruby/bin/gem" ]] && echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.zshrc
}
[[ "$(uname)" = "Linux" ]] && {
    hash dnf 2>/dev/null && {
        sudo dnf install -y neovim fish bat exa tokei hyperfine fd-find fzf tmux gcc gcc-c++ openssl-devel libgit2-devel cmake youtube-dl aria2 cockpit meson mosh nasm python3 python3-devel python3-pip ripgrep rsync ruby-devel rubygems plantuml graphviz zlib-devel dbus-glib-devel clang
        sudo dnf update -y
    }
    hash apt-get 2>/dev/null && {
        wget -qO - https://apt.thoughtbot.com/thoughtbot.gpg.key | sudo apt-key add -
        echo "deb https://apt.thoughtbot.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/thoughtbot.list
        apt-get update
        apt-get install -y neovim fish bat fd-find tmux gcc g++ libssl-dev libgit2-dev cmake youtube-dl aria2 meson mosh nasm python3 python3-dev python3-pip ripgrep rsync ruby ruby-dev plantuml graphviz zlib1g-dev libczmq-dev libdbus-glib1-dev clang libcairo2-dev libgirepository1.0-dev
        apt-get upgrade -y
    }
}
