#!/bin/bash
pip3 install --user --upgrade pip wheel
cat << EOPACKAGES | xargs pip3 install --user
isort
pylint
black
flake8
jupyter
jupyterlab
neovim
magic-wormhole
img2pdf
EOPACKAGES

pip3 list --outdated --format=freeze | grep -v '^\-e' | grep -v 'libcomps' | cut -d = -f 1  | xargs -n1 pip3 install --user -U
