#!/bin/sh
pip3 install --user isort pylint black jupyter jupyterlab neovim
pip3 list --outdated --format=freeze | grep -v '^\-e' | grep -v 'libcomps' | cut -d = -f 1  | xargs -n1 pip3 install --user -U
