#!/bin/bash
[[ "$(uname)" = "Darwin" ]] && {
    export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
}

cat << EOGEMS | xargs gem install --pre --user
asciidoctor
asciidoctor-pdf
asciidoctor-diagram
EOGEMS

cat << EOGEMS | xargs gem install --user
foreman
EOGEMS
